const {lightningDaemon} = require('ln-service');

const SSS_LND_GRPC_HOST = "54.153.106.53:10009";
const SSS_LND_MACAROON = "AgEDbG5kArsBAwoQcLvVm3aq2zIq2ciJBTezLBIBMBoWCgdhZGRyZXNzEgRyZWFkEgV3cml0ZRoT\n\
CgRpbmZvEgRyZWFkEgV3cml0ZRoXCghpbnZvaWNlcxIEcmVhZBIFd3JpdGUaFgoHbWVzc2FnZRIE\n\
cmVhZBIFd3JpdGUaFwoIb2ZmY2hhaW4SBHJlYWQSBXdyaXRlGhYKB29uY2hhaW4SBHJlYWQSBXdy\n\
aXRlGhQKBXBlZXJzEgRyZWFkEgV3cml0ZQAABiBp9ylaRBKvvBLM4QpASlW2d1b2quqZQPMSDHXO\n\
qrikyA==";


const SSS_LND_TLS_CERT = "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUIrVENDQVo2Z0F3SUJBZ0lRUm5LWk1TVktz\n\
UjVGMk54RnhXbGo3REFLQmdncWhrak9QUVFEQWpBOE1SOHcKSFFZRFZRUUtFeFpzYm1RZ1lYVjBi\n\
MmRsYm1WeVlYUmxaQ0JqWlhKME1Sa3dGd1lEVlFRREV4QnBjQzB4TnpJdApNekV0TVRndE1qUTRN\n\
QjRYRFRFNE1EVXhPREU1TVRRd09Wb1hEVEU1TURjeE16RTVNVFF3T1Zvd1BERWZNQjBHCkExVUVD\n\
aE1XYkc1a0lHRjFkRzluWlc1bGNtRjBaV1FnWTJWeWRERVpNQmNHQTFVRUF4TVFhWEF0TVRjeUxU\n\
TXgKTFRFNExUSTBPREJaTUJNR0J5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEEwSUFCQlJkS1p6eCt3\n\
MktEYlVGU0w1MQp6am1vbGV1WmZyZ0krbXVueG5qVGtuMmZEYjNXc1owc0FCVXIxU3NiNnA5MURC\n\
TFArTk82bkZQUWw2dDc1bnJVCm9xbWpnWUV3ZnpBT0JnTlZIUThCQWY4RUJBTUNBcVF3RHdZRFZS\n\
MFRBUUgvQkFVd0F3RUIvekJjQmdOVkhSRUUKVlRCVGdoQnBjQzB4TnpJdE16RXRNVGd0TWpRNGdn\n\
bHNiMk5oYkdodmMzU0hCSDhBQUFHSEVBQUFBQUFBQUFBQQpBQUFBQUFBQUFBR0hCS3dmRXZpSEVQ\n\
NkFBQUFBQUFBQUFGekUvLzZVZXU2SEJEYVphalV3Q2dZSUtvWkl6ajBFCkF3SURTUUF3UmdJaEFL\n\
N0JyVWRURFZ1dGhybWtnV0J3YmdFdU1WQ21oOWt0dFVDUzdtYlVoTytGQWlFQTBLN2cKTW1nOTJD\n\
bkhhZkphemR0eW1GUDZ4ZUo2K2wwd2JWSkgvTVpxUTBjPQotLS0tLUVORCBDRVJUSUZJQ0FURS0t\n\
LS0tCg==";

console.log(SSS_LND_MACAROON);

/** Get the Lightning Network Daemon connection

  {}

  @throws
  <Error> when daemon credentials are not available

  @returns
  <LND GRPC API Object>
*/
module.exports = ({}) => {
  try {
    return lightningDaemon({
      cert: SSS_LND_TLS_CERT,
      host: SSS_LND_GRPC_HOST,
      macaroon: SSS_LND_MACAROON,
    });
  } catch (e) {
    console.log(e);
    throw new Error('FailedToInitializedLightningGrpcApi');
  }
};

